const GET_APPOINTMENT_LIST_START: string = 'GET_APPOINTMENT_LIST_START';
const GET_APPOINTMENT_LIST_SUCCESS: string = 'GET_APPOINTMENT_LIST_SUCCESS';
const GET_APPOINTMENT_LIST_FAIL: string = 'GET_APPOINTMENT_LIST_FAIL';
const LOGIN_SUCCESS: string = 'LOGIN_SUCCESS';


export {
    GET_APPOINTMENT_LIST_START,
    GET_APPOINTMENT_LIST_SUCCESS,
    GET_APPOINTMENT_LIST_FAIL,
    LOGIN_SUCCESS
}