const GET_APPOINTMENT_LIST_START: string = 'GET_APPOINTMENT_LIST_START';
const GET_APPOINTMENT_LIST_SUCCESS: string = 'GET_APPOINTMENT_LIST_SUCCESS';
const GET_APPOINTMENT_LIST_FAIL: string = 'GET_APPOINTMENT_LIST_FAIL';
const AUTH_START: string = 'AUTH_START';
const AUTH_SUCCESS: string = 'AUTH_SUCCESS';
const AUTH_FAIL: string = 'AUTH_FAIL';
const AUTH_LOGOUT: string = 'AUTH_LOGOUT';



export {
    GET_APPOINTMENT_LIST_START,
    GET_APPOINTMENT_LIST_SUCCESS,
    GET_APPOINTMENT_LIST_FAIL,
    AUTH_START,
    AUTH_SUCCESS,
    AUTH_FAIL,
    AUTH_LOGOUT
}